_defaults: &defaults
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  include_repos:
    - meetcleo

  use_labels: true

money:
  <<: *defaults
  members:
    - AgentAntelope
    - contatc2
    - h-lame

  channel: "#money_squad"
