_defaults: &defaults
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  include_repos:
    - meetcleo

  use_labels: true

monet:
  <<: *defaults
  members:
    - AgentAntelope
    - fernandezvieira 
    - kkavita92
    - wilco3d

  channel: "#monet_squad"

squad_x:
  <<: *defaults
  members:
    - ClemCB
    - panagspirou
    - tomwhatmore

  channel: "#squad-x"
