_defaults: &defaults
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  include_repos:
    - meetcleo

  use_labels: true

monet:
  <<: *defaults
  members:
    - fernandezvieira
    - olivictor
    - RSijelmass
    - wilco3d

  channel: "#monet_squad"

gringotts:
  <<: *defaults
  members:
    - ClemCB
    - tomwhatmore
    - iconpin
    - flood4life

  channel: "#gringotts_internal"

odyssey:
  <<: *defaults
  members:
    - AgentAntelope
    - andreacfm
    - CliffAw
    - lucanioi
  
  channel: "#odyssey-dev"
