_defaults: &defaults
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  include_repos:
    - meetcleo

  use_labels: true

monet:
  <<: *defaults
  members:
    - AgentAntelope
    - RSijelmass
    - wilco3d

  channel: "#monet_squad"

gringotts:
  <<: *defaults
  members:
    - ClemCB
    - flood4life
    - kofibright
    - novotnyjakub
    - tomwhatmore
    - FriedSock

  channel: "#gringotts_internal"

odyssey:
  <<: *defaults
  members:
    - CliffAw
    - SaraBon
    - iconpin
    - tarawud
    - naeglinghaff

  channel: "#odyssey-dev"

security_alerts:
  <<: *defaults
  members:
    - "dependabot[bot]"

  channel: "#first-responders"
