_default_filters: &default_filters
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

monet:
  <<: *default_filters

  include_repos:
    - meetcleo

  members:
    - AgentAntelope
    - RSijelmass
    - wilco3d

  channel: "#monet_squad"

gringotts:
  <<: *default_filters

  include_repos:
    - meetcleo

  members:
    - ClemCB
    - davefrey
    - kofibright
    - sachimp
    - tomwhatmore
    - toypadlock
    
  channel: "#gringotts_internal"

odyssey:
  <<: *default_filters

  include_repos:
    - meetcleo

  members:
    - SaraBon
    - iconpin
    - tarawud
    - naeglinghaff
    - stevehook

  channel: "#odyssey-dev"

security_alerts:
  <<: *default_filters

  include_repos:
    - meetcleo

  members:
    - "dependabot[bot]"

  channel: "#first-responders"

data:
  <<: *default_filters

  include_repos:
    - analytics
  
  members: []

  channel: "#dbt-code-review"

lannisters:
  <<: *default_filters

  include_repos:
    - meetcleo

  members:
    - FriedSock
    - CliffAw
    - DhirenAtodaria
    - repoocuts

  channel: "#lannister-dev"
