_defaults: &defaults
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  include_repos:
    - meetcleo

  use_labels: true

core:
  <<: *defaults

  members:
    - bryonywatson1
    - cazwazacz
    - mijoharas

  channel: "#core_squad"

growth:
  <<: *defaults

  members:
    - bestan

  channel: "#growth_squad"

plus:
  <<: *defaults
  members:
    - AgentAntelope
    - fuzzmonkey
    - GeorgeA93
    - h-lame
    - jwblackwood

  channel: "#cleo_plus_squad"

mobile-app:
  <<: *defaults

  members:
    - hovlev
    - wilco3d
    - ablamunits
    - obates
    - gustavolobo

  channel: "#app_squad"
